version: "3"
services:
  #proxy:
  #  image: nginx
  #  container_name: nginx
  #  network_mode: "host"
  #  ports:
  #    - 80:80
  #    - 443:443
  #  volumes:
  #    - ./nginx:/etc/nginx
  #    - ./ssl:/ssl:ro
  #    - ./log:/log
  #database:
  #  image: 'postgres:12'
  #  container_name: postgres
  #  ports:
  #    - "5432:5432"
  #  network_mode: "host"
  #  env_file: 
  #    - .env
  #  environment:
  #    - POSTGRES_USER=admin
  #    - POSTGRES_PASSWORD=admin
  #    - POSTGRES_DB=V1
  #  volumes: 
  #    - db:/var/lib/postgresql/data
  client:
    build: 
      context: client
    image: client
    container_name: client
    ports:
      - "3002:3002"
    volumes:
      - ./ssl:/ssl:ro
    network_mode: "host"
  server:
    build:
      context: server
    image: server
    container_name: server
    ports:
      - "8001:8001"
    env_file: 
      - .env
    environment:
      - PG_HOST=192.168.9.97
      - PG_PORT=5432
      - PG_DBNM=V1
      - PG_USER=admin
      - PG_PASS=admin
    network_mode: "host"
    #depends_on:
      #- database
      #- proxy
#volumes:
#  db:
#    driver: local