apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatservice
  labels:
    app: chatservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
      - name: chatservice
        image: gcr.io/PROJECT_ID/chatservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: chatservice-secrets
              key: mongodb-uri
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: chatservice-secrets
              key: jwt-secret
        - name: SERVER_PORT
          value: "8080"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: RATE_LIMIT_RPM
          value: "100"
        - name: RATE_LIMIT_BURST
          value: "10"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: chatservice-service
spec:
  selector:
    app: chatservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: chatservice-secrets
type: Opaque
data:
  mongodb-uri: <base64-encoded-mongodb-uri>
  jwt-secret: <base64-encoded-jwt-secret>