version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=music
      - POSTGRES_PASSWORD=music
      - POSTGRES_DB=musicdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elt:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=musicdb
      - DB_USER=music
      - DB_PASS=music
    volumes:
      - ./data:/app/data
      - ./sql:/app/sql
    entrypoint: ["python", "elt.py"]

volumes:
  pgdata: